# Example PHP Schema file
# Use the following command to regenerate entities:
# bin/schema generate-types src/ app/config/schema.yml

annotationGenerators: # Generators we want to use, keep it as is for any API Platform project
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\PhpDocAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\DoctrineOrmAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\ConstraintAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\DunglasApiAnnotationGenerator

namespaces:
    entity: AppBundle\Entity # The default namespace for entities, following API Platform and Symfony best practices

types: # The list of type to generated (a PHP entity class by type will be generated)
    Thing:
        properties:
            name: ~
    Person:
        properties: {} # We don't want any specific property for a person except "name" inherited from Thing
